<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-COMcopier-c3c56907-e4a5-4a34-89a1-48a284d7a43a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="COMcopier.ConfigUI\**" />
    <Content Remove="COMcopier.ConfigUI\**" />
    <None Remove="COMcopier.ConfigUI\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.*" />
    <PackageReference Include="System.IO.Ports" Version="8.0.*" />
  </ItemGroup>
</Project>
